app_name: postgres-scaler
stage: prod
scaling_mode: direct
service_type: Postgres
provider_type: Ionos
metrics_source_type: Prometheus
ionos_config:
  username: $IONOS_USERNAME
  password: $IONOS_PASSWORD
  contract_id: $IONOS_CONTRACT_ID
  cluster_source:
    cluster_filter_name: ""
postgres_config:
  resources:
    cpu:
      min_cores: 4
      min_usage: 0.3
      max_cores: 16
      max_usage: 0.7
    memory:
      min_bytes: 12288
      min_usage: 0.3
      max_bytes: 32768
      max_usage: 0.7
prometheus_config:
  url: https://api.example.com
metrics_exporter_port: 9100