app_name: bbb-scaler
  stage: prod
  scaling_mode: direct
  service_type: BBB
  provider_type: Ionos
  metrics_source_type: Prometheus
  ionos_config:
    username: $IONOS_USERNAME
    password: $IONOS_PASSWORD
    contract_id: $IONOS_CONTRACT_ID
    server_source:
      dynamic:
        datacenter_ids: []
        server_name_regex: "bbb-.*"
  bbb_config:
    resources:
      cpu:
        min_cores: 2
        min_usage: 0.3
        max_cores: 6
        max_usage: 0.7
      memory:
        min_bytes: 12288
        min_usage: 0.3
        max_bytes: 32768
        max_usage: 0.7
      replicas:
        min_replicas: 1
        min_usage: 0.3
        max_replicas: 3
        max_usage: 0.7
    cycle_time_seconds: 60
    api_token: $BBB_API_TOKEN
  prometheus_config:
    url: https://grafana.example.com/api/datasources/proxy/uid/<uid>/
    token: $GRAFANA_TOKEN
  metrics_exporter_port: 9100