app_name: postgres-scaler
stage: prod
scaling_mode: heuristic
service_type: Postgres
provider_type: Ionos
metrics_source_type: Prometheus
ionos_config:
  username: $IONOS_USERNAME
  password: $IONOS_PASSWORD
  contract_id: $IONOS_CONTRACT_ID
  cluster_source:
    static:
      cluster_ids:
        - UUID
postgres_config:
  resources:
    cpu:
      min_cores: 1
      max_cores: 4
      min_usage: 0.2
      max_usage: 0.7
    memory:
      min_bytes: 4096
      max_bytes: 12288
      min_usage: 0.2
      max_usage: 0.7
  cycle_time_seconds: 60
prometheus_config:
  url: https://api.ionos.com/telemetry/
  token: $IONOS_METRICS_TOKEN
metrics_exporter_port: 9100
