app_name: postgres-scaler
stage: prod
scaling_mode: direct
service_type: Postgres
provider_type: Ionos
metrics_source_type: Prometheus
ionos_config:
  username: $IONOS_USERNAME
  password: $IONOS_PASSWORD
  contract_id: $IONOS_CONTRACT_ID
  cluster_source:
    cluster_name_regex: "ionos-dbaas*"
postgres_config:
  resources:
    cpu:
      min_cores: 4
      min_usage: 0.3
      max_cores: 16
      max_usage: 0.7
    memory:
      min_bytes: 12288
      min_usage: 0.3
      max_bytes: 32768
      max_usage: 0.7
  cycle_time_seconds: 60
prometheus_config:
  url: https://grafana.example.com/api/datasources/proxy/uid/<uid>/
  token: $GRAFANA_TOKEN
metrics_exporter_port: 9100
