app_name: bbb-scaler
service_type: BBB
provider_type: Ionos
metrics_type: Prometheus
ionos_config:
  username: $IONOS_USERNAME
  password: $IONOS_PASSWORD
  server_source:
    dynamic:
      datacenter_ids: [UUID]
      server_name_regex: ".*"
bbb_config:
  resources:
    cpu:
      min_cores: 4
      max_cores: 16
      max_usage: 0.7
    memory:
      min_bytes: 12288
      max_bytes: 32768
      max_usage: 0.7
  cycle_time_seconds: 60
  api_token: $BBB_API_TOKEN
prometheus_config:
  url: https://grafana.example.com/api/datasources/proxy/uid/<uid>/
  token: $GRAFANA_TOKEN
