app_name: bbb-scaler
service_type: BBB
provider_type: Ionos
ionos_config:
  username: $IONOS_USERNAME
  password: $IONOS_PASSWORD
  server_source:
    dynamic:
      datacenter_ids: 
        - "b760e735-975c-4a8c-b1f3-b0d9b18b82d6" # dbpinfra-dev-bbb
        - "638a3977-d5f2-4649-8ab5-d4b586d8c357" # dbpinfra-dev-bbb2
      server_name_regex: ".*"
bbb_config: 
  resources:
    cpu:
      min_cores: 4
      max_cores: 16
      max_usage: 0.7
    memory:
      min_bytes: 12288
      max_bytes: 32768
      max_usage: 0.7
  cycle_time_seconds: 60
  api_token: $BBB_API_TOKEN
