apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra-autoscaler.fullname" . }}-config
  labels:
    {{- include "infra-autoscaler.labels" . | nindent 4 }}
data:
  scaler_config.yml: |
    {{- .Values.autoscalerConfig | toYaml | nindent 4 }}
