name: 'Publish image to GHCR and Helm chart to GH pages on tag'

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

concurrency:
  group: scaler-main
  cancel-in-progress: true

jobs:
  publish_docker:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@25fc21e7cfec4e3c6a819b1e6207e6bde6004b5b # 8.4.1
    with:
      image_name: "infra-autoscaler"
      run_trivy_scan: true
      run_clamav_scan: true
      image_tag_generation: "version_git_tag"
      add_latest_tag: true
      container_registry: "ghcr.io"
      limit-severities-for-sarif: true
  publish_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@25fc21e7cfec4e3c6a819b1e6207e6bde6004b5b # 8.4.1
    secrets: inherit
    with:
      chart_name: infra-autoscaler
      helm_chart_version_generation: specified
      image_tag_generation: specified
      helm_chart_version: ${{ github.ref_name }}
      image_tag: ${{ github.ref_name }}
