name: 'Publish image to GHCR on push to branch'

on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: scaler-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@094a0e74897bef119a5a8fc73da781ff1f2274e6 # 8.4.2
    with:
      image_name: "infra-autoscaler"
      run_trivy_scan: true
      run_clamav_scan: true
      image_tag_generation: "ticket_from_branch"
      add_latest_tag: false
      container_registry: "ghcr.io"
      limit-severities-for-sarif: true
