name: "Scan Helm on push"

on:
  push:

concurrency:
  group: infra-autoscaler-scan-helm-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  scan_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@25fc21e7cfec4e3c6a819b1e6207e6bde6004b5b # 8.4.1
    permissions:
      contents: read
