name: "Scan Helm on push"

on:
  push:

concurrency:
  group: infra-autoscaler-scan-helm-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  scan_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@094a0e74897bef119a5a8fc73da781ff1f2274e6 # 8.4.2
    permissions:
      contents: read
