name: "Scan Helm on push"

on:
  push:

concurrency:
  group: infra-autoscaler-scan-helm-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  scan_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@d7318717e25b71a8204a5039ff93b591b42f69a6 # 8.4.0
    permissions:
      contents: read
